# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    cluster: 'portal'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.219.128:9093']
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/recording-rules.yml"
  - "/etc/prometheus/alerting-rules.yml"
  - "/etc/prometheus/*.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    relabel_configs:
      - target_label: env
        replacement: dev
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    consul_sd_configs:
      - server: '192.168.219.128:8500'
        services: []
        tags: ["portal","node-exporter"]
    relabel_configs:
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap

  - job_name: 'redis-exporter'
    consul_sd_configs:
      - server: '192.168.219.128:8500'
        services: []
        tags: ["portal","redis-exporter"]
    relabel_configs:
      - regex: __meta_consul_service_metadata_(.+)
        action: labelmap
